### ISSUE TITLE
HTTP 500 Error trying to install datatables-tabletools 2.2.4

### ISSUE THREAD

**Issue by douglascayers** [jamesward/forcewebjars#1]
Hi, great tool!

I'm trying to install datatables-tabletools 2.2.4 into my sandbox org via https://forcewebjars.herokuapp.com but receive HTTP 500 server error. The message says "This exception has been logged with id <strong>6m49o3elk</strong>."

I was able to install some other webjars fine, like jquery, jqueryui, and datatables.

Thanks

**Comment by jamesward** [comment]
Thanks for reporting this.  The problem is that I added the Bower WebJars and these showed up in the list but weren't actually supported.  You should be able to use the classic `datatables-tools` WebJar instead.

Fixing this shortly.
